version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SentiVerse
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  hangfire:
    image: hangfireio/hangfire:1.7.36
    environment:
      - Hangfire__Dashboard__Authorization__IsEnabled=true
    ports:
      - "8082:80"
  api:
    build: .
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Database=SentiVerse;Username=postgres;Password=postgres
      Jwt__Key: SuperSecretKey12345
      EmotionApi__BaseUrl: http://ai-sentiment-api
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:80"
