name: sentiverse
description: A real-time emotion group chat app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.14.0
  flutter_secure_storage: ^8.0.0
  signalr_core: ^1.1.1
  flutter_form_builder: ^9.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
